### PR TITLE
feat: YouTube controller design layout for embed videos

### LINKED ISSUE #1103: Use YouTube player controls when playing back a YouTube video
We should use the standard YouTube video controls when playing back YouTube videos. 

See https://github.com/mitodl/hq/discussions/418 for a full discussion of the reasoning behind this decision. 

#### Designs and Mockups

Switching to the YouTube controls means that we have to move the download button outside of the video player

See these InVision designs for the new location and behavior:
- https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347461/preview
- https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347462/preview

#### Acceptance Criteria:

- [x] When a video is streamed from YouTube, use the YouTube controller (note: all our videos stream from YouTube at this time) 
- [x] While it is rare, it is possible for a video to have no interactive captions. In that case, the "Transcript" button should not be displayed, but the download button should still be available. 
- [x] remove the extra space to the left of the interactive transcript, so it left aligns with the video player (see [InVision Comment](https://projects.invisionapp.com/d/#/console/21537330/472347462/comments/150602733))
- [ ] YouTube controller and the design changes should also work for embedded videos (eg., see this [embedded video page](https://ocw.mit.edu/courses/res-18-009-learn-differential-equations-up-close-with-gilbert-strang-and-cleve-moler-fall-2015/pages/video-series-overview/))

#### Related issues

- Switching to the YouTube controller should also close #978

### PR DESCRIPTION
**Pull request by ibrahimjaved12**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1103 and https://github.com/mitodl/hq/issues/1196

#### What's this PR do?
This PR updates design layout for embed videos. It also fixes the bug issued in https://github.com/mitodl/hq/issues/1196 by updating youtubeParams.

#### How should this be manually tested?

For any of these changes (start time, end time, or general layout related changes), sometimes they can take a little time even after clearing cache and using incognito window. If it still does not work, try clearing cache a couple of times, give it a minute or two, and then try again.

Firstly, follow the testing steps on [this PR](https://github.com/mitodl/ocw-hugo-themes/pull/1115). They will be repeated exactly as they are, but you will be checking out to this branch instead.

Next, we will have to test a sample course to test for embed videos. And we will also be testing that `start_time` and `end_time` of videos are functioning properly with the new changes. 

Clear cache, and use new incognito window.
Use this course: [18.02sc-fall-2010](https://github.mit.edu/ocw-content-rc/18.02sc-fall-2010)
1. Checkout to this branch
2. Make sure you update the above course in your .env
3. Run `yarn start course`
4. Go to this link: http://localhost:3000/pages/2.-partial-derivatives/part-a-functions-of-two-variables-tangent-approximation-and-optimization/session-27-approximation-formula/
Note: You can do the next step (5) in combination of step (7) to save time.
5. For the recitation video (embed video), Make sure the YouTube controls are working + "VIEW VIDEO PAGE" is in black tab bar (clickable) + Download icon is there with "Download video" and "Download transcript" links. The look should match the InVision designs in these links:
https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347461/preview
https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347462/preview
6. We will also make sure our single video YouTube controller is also working on embed video courses: Go to this link http://localhost:3000/resources/clip-approximation-formula/ and make sure the changes you tested in the above PR are also prevalent on this link. 
7. Now we will edit `start_time` and `end_time` for all their possible combinations for the recitation video in step 4. Values for all combinations can be: `{(ST: 5, ET: 9), (ST: 5, ET: ''), (ST: '', ET: 9), (ST: '', ET: '')} `
8. Go to this markdown file for the recitation video in your local ocw-content-rc directory: `18.02sc-fall-2010/content/resources/tangent-plane-approximation.md`
9. You will see that currently the `start_time` and `end_time` are set to empty in the markdown file. Test the video in step 4 for this case. Similarly test for the remaining 3 test cases in (7) step by editing the video's markdown file and saving it. Terminate the project and run `yarn start course` for each of the test case (along with clearing cache measures). Make sure that the video starts to the given `start_time`, and **automatically** ends at the given `end_time` (if you force this behavior through keyboard arrow keys, the video will not end at the given end time. So let the video end naturally at the given end time mentioned in the file)

#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Comment by pdpinch** [comment]
I'd really like to get this merged asap, but I have to ask -- does our test course for playwrite testing include this type of markdown data?

**Comment by ChristopherChudzicki** [comment]
@pdpinch @ibrahimjaved12  re 
> I'd really like to get this merged asap, but I have to ask -- does our test course for playwright testing include this type of markdown data?

> If it doesn't, maybe that can be an issue for later.

It does not, but it should.

We're a little limited in terms of what we can actually test with the youtube player, since I doubt playwright can make any meaningful assertions about what is inside the iframe. But we can certainly test things like
- transcript start/end times are correct
- iframe has the expected `start/end/controls` query parameters.

I'll make an issue for this.

**Review by ChristopherChudzicki — APPROVED** [review]
Looks good!

@ibrahimjaved12 BTW, if you have not found this yet, you can start a particular course with its shortid. For example:

```
yarn start course 18.02sc-fall-2010
```

**Comment by ibrahimjaved12** [comment]
> Looks good!
> 
> @ibrahimjaved12 BTW, if you have not found this yet, you can start a particular course with its shortid. For example:
> 
> ```
> yarn start course 18.02sc-fall-2010
> ```

Thanks @ChristopherChudzicki. I did know of this but hadn't tried it yet, had gotten used to the other approach. I'll try this!

**Pull request merged**
