### PR TITLE
moved resource link to base theme

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
Adds resource_link shortcode  to base theme to fix failing builds.

### CODE REVIEW

**Comment by pdpinch** [comment]
Is this ready for review?

**Comment by wassafshahzad** [comment]
> Is this ready for review? 

Yes

**Comment by Wassaf-Shahzad** [comment]
> Is this ready for review?

yes

**Review by ChristopherChudzicki — APPROVED** [review]
👍 Cool, I was going to make a PR for this today for a separate reason!

**Pull request merged**
