### PR TITLE
fix: placing mp_logo in static images of course theme

### PR DESCRIPTION
**Pull request by MAbdurrehman12**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
closes https://github.com/mitodl/ocw-hugo-themes/issues/289

#### What's this PR do?
Creates directory of static and images (inside static) in course theme and places the logo inside it so it can be rendered in any course.

#### How should this be manually tested?
- Go to any course which uses this logo and verify that logo image is showing instead of alt text "Buy at MIT Press". (course [21g.049-spring-2017](https://github.mit.edu/ocw-content-rc/21g.049-spring-2017) use this logo in pages/assignments/presentations-and-sources/ under section of week 5)

#### Screenshots (if appropriate)
Before:
image

After: 
image

### CODE REVIEW

**Review by abeglova — APPROVED** [review]
LGTM

**Comment by MAbdurrehman12** [comment]
@gumaerc I tested it locally and it was working fine but didn't work in https://github.com/mitodl/ocw-hugo-themes/pull/359, Have I placed the image in correct place or there's something else that needs to be done in order to make this image part of deployment?

**Comment by gumaerc** [comment]
@MAbdurrehman12 I see the image in the latest [theme assets build](https://cicd-qa.odl.mit.edu/teams/ocw/pipelines/ocw-theme-assets/jobs/build-theme-assets/builds/5?vars.branch=%22release-candidate%22) but the [`ocw-www` build](https://cicd-qa.odl.mit.edu/teams/ocw/pipelines/live/jobs/build-ocw-site/builds/82?vars.site=%22test-ocw-www%22) was paused at some point on Sunday by @mbertrand, likely for troubleshooting reasons.  I unpaused the pipeline and triggered a build, which should deploy the latest theme assets to https://ocwnext-rc.odl.mit.edu.

**Comment by MAbdurrehman12** [comment]
Alright.
Thanks for informing.

**Comment by MAbdurrehman12** [comment]
@gumaerc I wonder if the image was deployed to assets as it doesn't seem to appear [here](https://ocwnext-rc.odl.mit.edu/courses/21g-049-french-photography-spring-2017/pages/assignments/presentations-and-sources/).

**Pull request merged**
