### PR TITLE
feat: compact footer

### PR DESCRIPTION
**Pull request by MAbdurrehman12**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
closes https://github.com/mitodl/ocw-hugo-themes/issues/861

#### What's this PR do?
- Introduces a new compact footer (aka footer-v2)
- Currently, footer-v2 files have been created in `base-theme` so if we have to use them in other themes (www, course-offline), we can use them without creating them again.

#### How should this be manually tested?
- Checkout this branch OR visit [netlify deployed version](https://ocw-hugo-themes-course-v2-pr-868--ocw-next.netlify.app/)
- Verify that the footer in CHP and other interior pages is according to the [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/469768935/preview?scrollOffset=0)
- Verify that all the links/buttons on the footer are working and redirecting to the correct locations.
- Verify that all the content/text on footer is correct (grammatically too) 
- Verify that footer is completely responsive on all screen sizes.
- Verify that footer is working fine on all browsers.

#### Screenshots (if appropriate)

screencapture-localhost-3000-2022-09-28-16_54_25

image

image

### CODE REVIEW

**Comment by MAbdurrehman12** [comment]
Note for the reviewer: 
- In design, the social icons are greyish, but we only have black ones so I have dropped a comment on the design, asking Nicolae for gray icons. Will replace them as soon as we get them.
- The `open education global` logo is blur but this is what we have so I have asked Nicolae for a clearer one.

**Review by Wassaf-Shahzad — CHANGES_REQUESTED** [review]
- Padding between "MIT Open Learning" image and "over 2500 courses and material" should be 27px currently its 14px using `ml-md-5` will work.
- @pdpinch  We need some guidelines on how the footer should behave on a tab's screen. Since at those widths the footer looks a bit awkward.
### Screenshots
Screenshot 2022-09-29 at 4 54 26 PM
Screenshot 2022-09-29 at 4 50 35 PM

**Comment by pdpinch** [comment]
> We need some guidelines on how the footer should behave on a tab's screen. Since at those widths the footer looks a bit awkward.

There seems to be a lot of white space in the middle. Can we keep the lines longer for tablets and wrap less?

**Comment by MAbdurrehman12** [comment]
@Wassaf-Shahzad Can you have another look, please?
@pdpinch Do we have any designs for small screens? (mobile, tablets etc)

**Review by gumaerc — APPROVED** [review]
:+1: 

This looks good to me. I didn't see any designs in Invision for mobile specifically but in my testing it looked good.

**Review by pdpinch — APPROVED** [review]
I took a look on netlify, and the design looks good to me.

**Pull request merged**
