### PR TITLE
Removed italic styles from instructor insights block quotes

### LINKED ISSUE #412: standardize blockquote styling
Blockquotes should look the same everywhere, on all courses. 

#### Designs and Mockups

For now, they should look like the style used in the instructor insights pages, i.e. 
InVision: https://projects.invisionapp.com/share/WG12918LUX7S#/screens/442724922_OCW_Instructor_Insights_Teaching_Heuristics_1-19-21
implemented: https://ocwnext.odl.mit.edu/courses/6-034-artificial-intelligence-fall-2010/pages/instructor-insights/teaching-heuristics/

#### Acceptance Criteria:

- [ ] Pure CSS implementation, applies all `<blockquote>` tags
- [ ] Works with output from ocw studio (see https://github.com/mitodl/ocw-studio/issues/953 )

#### Out of Scope

- No change to the ocw-www theme, at least for now

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #412

#### What's this PR do?
Removed italic styling from caption in blockqoutes

#### How should this be manually tested?
- Start ocw-courses
- Open instructor-insights and verify blockqoutes captions have font-style: normal

#### Any background context you want to provide?
Although, I have removed styles from course-v2 instructor-insights.scss but for me it did not work until i fixed styles in instructor-insights.sccc for course (v1).  I possible please do test if this PR works for you.

#### Screenshots (if appropriate)
(Optional)
Screenshot 2022-08-17 at 5 28 10 PM

### CODE REVIEW

**Comment by Wassaf-Shahzad** [comment]
@pdpinch I was a bit confused by the issue description and just to verify, do we only need to remove styles from the caption ?

**Comment by pdpinch** [comment]
Hi Wassaf. Let's put a pause on this so I can get some design input from the designer.

**Comment by ChristopherChudzicki** [comment]
@pdpinch Is this a style change we still want?

I don't think Abdurrehman is going to review it, and Wassaf probably won't bug anyone new :)

**Comment by ChristopherChudzicki** [comment]
Per @pdpinch comment

> Let's put a pause on this so I can get some design input from the designer.

I'm going to close this. It's a two line change, so if we decide to make it, it's easy enough to do without this PR.

**Pull request closed without merging**
