### PR TITLE
updated 404 page

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Part of #608

#### What's this PR do?
- Moves all the code for the external css to the 404 page itself

#### How should this be manually tested?
- Verify 404 page does not depend on any external css.

#### Screenshots (if appropriate)
Screenshot 2022-05-31 at 4 30 42 PM

### CODE REVIEW

**Comment by pdpinch** [comment]
Is it possible to include the site header and footer? (Sorry if I asked this before)

**Comment by pdpinch** [comment]
> I would probably need to add CDN links to bootstrap and JQuery

I get bootstrap, but why jquery?

In any case, not a blocker.

**Comment by Wassaf-Shahzad** [comment]
> > I would probably need to add CDN links to bootstrap and JQuery
> 
> I get bootstrap, but why jquery?
> 
> In any case, not a blocker.
We dont need jquery if we are using bootstrap 5 but some components in bootstrap 4 require it https://www.w3schools.com/bootstrap4/bootstrap_get_started.asp#:~:text=Bootstrap%204%20use%20jQuery%20and,you%20don't%20need%20them.

I am certain that we dont use any jquery for the footer but I am not sure about the header

**Comment by gumaerc** [comment]
I think we still have a few lingering dependencies on JQuery and Popper that we would need to deprecate / work around, but we should definitely upgrade to Bootstrap 5 at some point.  As evidenced by Paul's recent trouble spinning up `ocw-studio` on an M1 Mac, we don't go through our projects and upgrade dependencies often enough, at least not until it gets to the point where it causes a technical problem.

This being said, with the goal just being to get a static 404 page working, I think it's okay to create something like a `404_header.html` and `404_footer.html` that preserves the design in the most minimal and inlined way possible.  Looking at the templates, I think the reason we need Bootstrap here are automatically handling layout switching and bringing in the hamburger menu for mobile.  If we could imbed some CSS media queries to accomplish a minimal version of the same thing here, I think that would be fine.  Maybe on the 404 page header, we don't need a hamburger menu but instead could just have a link to the home page on the header image that will bring them there where the whole site is available?

**Comment by pdpinch** [comment]
We're spending way too much time on this. Let's merge as is and I'll decided later if I really want a header and a footer.

**Pull request merged**
