### PR TITLE
OCW Stories & Quotes New Design Implementation

### PR DESCRIPTION
**Pull request by ibrahimjaved12**
### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/1384
Please note that there is a lot discussion in the ticket, most of which is not relevant anymore. So you may want to just focus on the Figma designs for this PR.

### Description (What does it do?)
Implements redesign of OCW Stories & Quotes. It includes:
- Homepage
- Stories List Page 
- Stories Single Page

Figma designs: 
[Desktop](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1035-438&starting-point-node-id=1035%3A438&scaling=min-zoom&content-scaling=fixed&t=YOKK0Xzmq2MUBxcn-1)

[Homepage](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1035-438&node-type=frame&viewport=688%2C429%2C0.18&t=CQwi9vRTa9xAQi10-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1035%3A438) - Desktop
[Stories Listing page](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1035-522&node-type=frame&viewport=688%2C429%2C0.18&t=CQwi9vRTa9xAQi10-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1035%3A438) - Desktop
[Story Detail page](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1035-473&node-type=frame&viewport=688%2C429%2C0.18&t=CQwi9vRTa9xAQi10-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1035%3A438) - Desktop

[Home section](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1400-554&node-type=frame&viewport=584%2C441%2C0.14&t=Or4UeHQtnx3pM7Er-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1400%3A554&show-proto-sidebar=1) - Mobile
[Stories listing page ](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1400-642&node-type=frame&viewport=584%2C441%2C0.14&t=2pBevSc14lpf89Al-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1035%3A438&show-proto-sidebar=1)- Mobile - the only change is the header, rest of the story listing will remain same as the home cards.
[Story Detail page](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Stories?page-id=1035%3A386&node-id=1400-1104&node-type=frame&viewport=584%2C441%2C0.14&t=2pBevSc14lpf89Al-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1035%3A438&show-proto-sidebar=1) - Mobile

### How can this be tested?
Test the following links:

- [Homepage](http://localhost:3000/)
- [All Stories Page](http://localhost:3000/stories/)
- [Random Story Example](http://localhost:3000/stories/demetra-tzevelekos/)

1. Checkout to this branch. 
2. `yarn start www`
3. Make sure things are working as expected in the Figma designs. 
4. Test the changes across all screen sizes to confirm they are responsive and visually consistent. 
5. Ensure all homepage features in www theme are working as before, especially carousel in Featured Courses/New Courses/OCW Stories.
6. Although quotes functionality relies on backend implementation (which will be done shortly next), it can still be tested. Add the following fields to the frontmatter of a markdown file for a story:
```
is_quote: true
leadquote: Your quote here
```
7. Ensure the Quotes Modal opens and functions as intended.

### Screenshots
I made some minor padding/margin related changes after taking these screenshots. The overall look is more or less same. But for exact changes, please refer to the PR deployment link: https://ocw-hugo-themes-www-pr-1460--ocw-next.netlify.app/

### Desktop screenshots
Single page: 
image
image
(There are 4 cards on right)

List page:
image
image

Homepage:
image

Quotes card:
image

### Medium screen:
Homepage:
image

List page:
image
image

Single page:
image
image

Quotes card:
image

### Small screen:
Quotes card:
image

Homepage:
image

Single page:
image
image

List page:
image
image

### CODE REVIEW

**Comment by pdpinch** [comment]
What are the recommended image dimensions (going forward)?

**Comment by ibrahimjaved12** [comment]
> What are the recommended image dimensions (going forward)?

@pdpinch 
@mbilalmughal Recommended to use 16:9 ratio, which we did in this PR.

But in the existing story pictures, we were having some challenges getting the faces of people aligned properly with this ratio. Because we previously used like 1:1 ratio (square) and the images were conforming to this.

I used some CSS to adjust this.

Before:
image

After:
image

Property used:
`object-position: 50% 25%;`
This centers the image horizontally center, and vertically shifts 25% down from the top.

So even with this, we're going to have a few outliers in our existing data. But if necessary, this can be easily manually fixed for the 6-7 problematic pictures. Moving forward, as long as the faces in the images are positioned in the upper area and not too zoomed in, this approach should work well with the recommended 16:9 ratio.

**Comment by ibrahimjaved12** [comment]
@pdpinch @mbilalmughal 
I added 2 Quotes Cards (Black Cat and White Cat) in `ocw-www` rc site and re-ran the deployments of this PR.

Everything can also be checked from the deployment link: https://ocw-hugo-themes-www-pr-1460--ocw-next.netlify.app/
The quote cards are the 2nd card and the last card (you can use left navigation from carousel).

**Comment by mbilalmughal** [comment]
> @pdpinch @mbilalmughal I added 2 Quotes Cards (Black Cat and White Cat) in `ocw-www` rc site and re-ran the deployments of this PR.
> 
> Everything can also be checked from the deployment link: https://ocw-hugo-themes-www-pr-1460--ocw-next.netlify.app/ The quote cards are the 2nd card and the last card (you can use left navigation from carousel).

I have review all the UI changes/updates, LGTM

**Pull request merged**
