### PR TITLE
video player styling for course v2

### PR DESCRIPTION
**Pull request by MAbdurrehman12**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/802

#### What's this PR do?
- Updates the style of video progress bar so it covers the complete width of video player.
- Updates toggleable tabs under the video to make them uniform/same. (`Related resources` and `optional` tab's UI made same as of `transcription` tab UI)

#### How should this be manually tested?
- Checkout this branch
- Build any course on new course theme, i.e: course-v2 (more detail in this [PR](https://github.com/mitodl/ocw-hugo-themes/pull/784)) which has videos, transcript, related resources and optional tab.
- Verify that video progress bar covers the complete width of video player.
- Verify that all the 3 toggleable tabs are same in terms of UI and functionality and they work as expected.
- Repeat the above steps on different browsers and different screen sizes. 
- **Important:** Verify that things in the previous course theme are working like before and this PR has no impact on that.

#### Screenshots (if appropriate)
image

image

image

### CODE REVIEW

**Comment by MAbdurrehman12** [comment]
@pdpinch I'm thinking of giving some margin from left and bottom to the content of `Related Resources` and `Optional` (Lecture Notes) tabs too, similar to what we have in the above transcript tab. 

image

Do you have any thoughts on this? or on the overall design?

**Review by gumaerc — APPROVED** [review]
@MAbdurrehman12 I'm going to approve this because the changes to the video player look mostly good and don't affect the player in the regular `course` theme, but there are some caveats:

 - Firstly, I noticed in Chrome that the transcript has a stock browser scrollbar on the right side that seems to be indented and looks kind of out of place:
 
 
image
 
 - Secondly, and this is probably more related to changes in `abdurrehman/compact-design`, I noticed that the v2 header seems to be applied even if I am not including `course-v2` in my config:
 
image
vs
image

The scroll bar issue is something we might want to look into in this PR before we merge it to the compact design branch, but the header issue should obviously be looked into on that branch directly rather than here.  Either way, if you want to merge this and then address those problems separately I'm fine with that too.

**Comment by pdpinch** [comment]
> @pdpinch I'm thinking of giving some margin from left and bottom to the content of Related Resources and Optional (Lecture Notes) tabs too, similar to what we have in the above transcript tab.

I don't love it, but I we do need some separation, so folks know they can click and also so they have enough space between tappable areas (a mobile requirement). 

I think you should indent of contents of the hide/show the same amount. 

image

**Comment by MAbdurrehman12** [comment]
@gumaerc Thanks for having a look into it.
I have updated the PR with this [feedback](https://github.com/mitodl/ocw-hugo-themes/pull/803/#issuecomment-1194483602) along with some other tweaks.

Regarding your point of scrollbar: I agree, it doesn't look really good but I think its the default one. 
Since I'm using mac so I have this type of default scrollbar:
Screenshot 2022-07-27 at 11 45 02 AM

However, if you think that we should customize this default scrollbar then I'd suggest doing it in other places too (i.e: page scrollbar or any other place where we have a scrolling section or page) for better consistency. And I think this can be done by a separate PR.

What do you think?

Perhaps @pdpinch could also share his thoughts?

**Review by gumaerc — APPROVED** [review]
@MAbdurrehman12 The updates look great; the indentation in the related resources section now matches the video time stamps.  While the scrollbar in Linux and Windows does indeed look kind of ugly, my feedback on that was more that it isn't flush with the right side of the container.  It's not really my place to say whether or not this matters, but it feels weird to me for a scroll bar to not be flush with the side of the container it's scrolling.  What do you think @pdpinch?  Either way, we can merge this as is if it matches the design.

**Comment by MAbdurrehman12** [comment]
> my feedback on that was more that it isn't flush with the right side of the container

Ahh right. Thanks for pointing it out. I also did not notice it.
Anyhow, I've updated the PR to push it to the right-most side.
I think we can merge this now!

**Review by gumaerc — APPROVED** [review]
:+1: LGTM

**Pull request merged**
