### PR TITLE
Remove unused dialog

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
None

#### What's this PR do?
Removes some HTML which was there for a dialog which isn't displayed anywhere. 

#### How should this be manually tested?
Nothing should appear different

### CODE REVIEW

**Review by annagav — COMMENTED** [review]
Do we still need the `beta-dialog` style?

**Comment by noisecapella** [comment]
@annagav good catch, I removed that style too

**Comment by noisecapella** [comment]
@annagav any other comments?

**Review by annagav — APPROVED** [review]
👍

**Pull request merged**
