### PR TITLE
feat: new design for course expand and collapse

### PR DESCRIPTION
**Pull request by MAbdurrehman12**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/286

#### What's this PR do?
New design for expanding and collapsing course description, course meta-data and image description.

#### How should this be manually tested?
- Verify that image description, course description and course info (meta-data) expands and collapse correctly when arrow icon is clicked/toggled.
- Change the size of the content or test them on different courses having different sizes/lengths of content.
- Test the above on multiple browsers and multiple screen sizes.

#### Screenshots (if appropriate)

All three, image description, course description and info closed:
image

Image Description open and course description and info closes:
image 

Both, Course description and info open:
image

info open and course description closed:
image

### CODE REVIEW

**Comment by pdpinch** [comment]
If you are stuck on the image description, you can save that for a separate PR, so we can get this reviewed and merged.

**Comment by MAbdurrehman12** [comment]
> If you are stuck on the image description, you can save that for a separate PR, so we can get this reviewed and merged.

Thanks, but image description is also almost wrapped up so I'll finalise this PR

**Review by alicewriteswrongs — APPROVED** [review]
lgtm! 👍

**Comment by MAbdurrehman12** [comment]
@pdpinch This PR has been reviewed by Alice, should we merge this one or the [other one](https://github.com/mitodl/ocw-hugo-themes/pull/330) (having smooth expand/collapse)?

**Comment by MAbdurrehman12** [comment]
Closing this PR as it's enhancement PR (https://github.com/mitodl/ocw-hugo-themes/pull/330) has been merged.

**Pull request closed without merging**
