### PR TITLE
About Us Page

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [ ] Testing
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/278

#### What's this PR do?
This PR adds the About Us page to the `ocw-www` theme, based on the designs in the attached issue.  It adds the milestone cards and OCW staff as new types of content, so they can be easily managed in the future and / or brought under CMS control.

#### How should this be manually tested?
 - Review the designs in the attached issue for mobile in desktop
 - View the PR [preview deploy of the page](https://ocw-hugo-themes-pr-303--ocw-next.netlify.app/about)
 - Verify that the look of the page is as close to the designs as possible
 - Try out the sub-nav on desktop and mobile, make sure it skips to the intended sections
 - Try out the milestone and staff carousels on mobile
 - Verify that links on the page go where they should
 - Verify that the embedded videos play
 - Repeat the above for as many browsers as you have access to, as well as at mobile resolutions

#### Screenshots (if appropriate)
desktop-1
desktop-2
desktop-3
desktop-4
desktop-5
desktop-6
desktop-7
desktop-8
desktop-9
desktop-10
mobile-1
mobile-2
mobile-3
mobile-4
mobile-5
mobile-6

### CODE REVIEW

**Review by MAbdurrehman12 — COMMENTED** [review]
Overall, everything looks great! However, I had a chance to go over the design a bit and noticed few things which I can share:

**Desktop:** 

The text in "The OCW@20 Vision" section seems to a bit bolder as compared to the design. (since I'm not having access to inspect the design so I'm not very sure about the font-size, but please feel free to ignore this if the font sizes are matching).

Netlify SS:
image

Design SS:
image
--------------------------------
Links in "OCW Milestones" sections are black instead of blue

Netlify SS:
image

Design SS:
image
--------------------------------
"Beyond course materials" section's image touching "President's Mesasge":

Netlify SS:
image

Design SS:
image
--------------------------------
"President's message" section's background color seems to differ (again, I'm not having the actual design color codes so please feel free to ignore this if color codes are already matching)

Netlify SS:
image

Design SS:
image
--------------------------------
on-page-nav buttons seems to jump to the appropriate sections instead of smooth scrolling.

Netlify SS:
image

--------------------------------

**Mobile:**

hamburger menu icon not working

Netlify SS:
image
--------------------------------
on smaller screens, on-page-nav button does not take to the start of the section, it goes a bit down  instead of jumping/scrolling to the start of section.

Netlify SS: 
Image from iOS
--------------------------------
On first time: carousels does not work/slide with thumb, but once a right or left button is clicked then they also slide with thumb afterwards (it looks quite strange so not sure if there's any issue on my end).

--------------------------------
If my PR review is not according to the standard process or if there's any issue in it then please feel free to make any corrections/suggestions in my approach of reviewing PR.

**Comment by gumaerc** [comment]
@MAbdurrehman12 Thanks for the review, I'll take a look at these comments today.

**Comment by pdpinch** [comment]
FYI, there is a separate issue for the hamburger / sandwich menu, #26

**Comment by pdpinch** [comment]
Let's keep the link styling consistent: black everywhere.

**Comment by MAbdurrehman12** [comment]
@gumaerc Sorry, I forgot to mention 1 thing: 
In navbar, when we click "About OCW", it redirects us to the correct page but it also shows the "Coming soon" tooltip

**Comment by gumaerc** [comment]
@MAbdurrehman12 I'm signing off for winter break and won't see this until we're back in January, but I made some adjustments:

 - You were right about the "OCW@20" section font, it's supposed to be "Helvetica Light" so I switched it to that
 - Padding was adjusted in various sections to better match the design, especially in the "beyond course materials" section where you noted it was running up against the president's message section
 - I was able to reproduce the issue you noted about swipe gestures on the carousels and fixed that
 - I reworked the subnav scrolling to take the height of the subnav bar into account (it was scrolling too far because it's `position: sticky` and hovers above everything) and changed the behavior to smooth scroll
 
 Some things that I did not end up adjusting:
 
 - As @pdpinch noted above, a while back with our old designer we had standardized on links being black across the site.  He's reaching out to our current designer to discuss this with him but we're going to leave them black for now.
 - The text in the President's Message section in the design has `#FFFFFF` set as the text color and `#000000` as the background color (pure black and white) and that's what I'm set, so I'm not sure why you're seeing a difference here.  As far as font family / sizes, the design has "Helvetica Regular" so I'm using the default `font-family: Helvetica" there.  The font size in desktop is 28px, and mobile is 18px.  When I put these in CSS, I convert them to `em` units based on a root font size of 16px so we can have responsive font sizes depending on the pixel density of the screen the text is being rendered on, so this ended up being 1.75em for desktop and 1.125em for mobile.  The font weight in the design does look slightly lighter than the Helvetica web font, but this could be a difference between the particular "flavor" of Helvetica invision is using vs the web font.  I have the feeling this is the case with it being called out as "Helvetica Regular" instead of just "Helvetica."
 
 Thanks for the feedback and let me know if you notice anything else or have any questions about the way the site is structured!

**Comment by MAbdurrehman12** [comment]
> 

Great work Carey!
Sure, enjoy your winter break to the fullest.
See you in 2022!

**Review by MAbdurrehman12 — APPROVED** [review]
👍

**Pull request merged**
