### PR TITLE
add fields theme

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/669

#### What's this PR do?
This PR adds a new theme called `fields`.  It allows you to create a site focused on a field of study, essentially making a home page out of a collection.

#### How should this be manually tested?
 - Create a site in [`ocw-studio-rc`](https://ocw-studio-rc.odl.mit.edu/sites) using the `mit-fields` starter.  This has been manually created in RC for testing purposes and the `ocw-hugo-projects` PR has not been created yet to codify it.
 - Clone `ocw-hugo-projects` on the `cg/mit-fields` branch
 - Visit the "Subfields" section and define as many subfields as you want, adding a list of courses to each one
 - Visit the "Field" section and fill out the info about the field site you are creating, selecting a featured Subfield and adding as many other subfields as you want
 - When you are done editing, publish your site.  Publishing will fail because this PR has not yet merged and the `ocw-hugo-projects` PR has not been created yet, but we don't need that for testing.
 - Find your site at https://github.mit.edu/ocw-content-rc/ and clone it locally
 - Set the following environment variables in your `.env` file, replacing `/path/to` with your path to the repos indicated and `your-field-slug` with the folder your course was cloned into in a previous step:
   - `FIELDS_HUGO_CONFIG_PATH=/path/to/ocw-hugo-projects/mit-fields/config.yaml`
   - `FIELDS_CONTENT_PATH=/path/to/ocw-content-rc/your-field-slug`
   - `STATIC_API_BASE_URL=https://ocw-draft-qa.global.ssl.fastly.net/` (for loading content from a static API for the courses linked in your Subfields)
 - Start the site with `npm run start:fields` and visit it at http://localhost:3000
 - Ensure that your field site displays properly and that you can visit the courses linked
 - Read the readme changes and ensure they make sense

#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Comment by gumaerc** [comment]
@ChristopherChudzicki They're supposed to have the same options, but in the featured subfield you can only choose one.  I just noticed that I neglected to set this in my test site that I generated the screenshots with, but it basically just determines which of the subfields has its course displayed at the top as the "featured courses list" just like collections in `ocw-www`.

image

**Comment by Ferdi** [comment]
@gumaerc i think it should be "featured courses", not "featured subfield"

**Comment by Ferdi** [comment]
"subfields" if you can.

**Comment by gumaerc** [comment]
@Ferdi Okay, that's basically what we have now then.  The collection in the starter I'm working on is called "Subfields" and you define a list of courses to be associated with it.  The "Featured Courses" field references the subfield collection, but is referred to as "Featured Courses."  Does that sound okay?

```
          - collection: subfield
            display_field: title
            label: "Featured Courses"
            multiple: false
            name: featured-courses
            sortable: false
            widget: relation
```

**Comment by gumaerc** [comment]
@ChristopherChudzicki Did you mean to approve this?  I think it's good to go now.

**Review by ChristopherChudzicki — APPROVED** [review]
@gumaerc Ack Yes, I thought I had approved it. Sorry!

**Pull request merged**
