### PR TITLE
fix: expand description button style

### PR DESCRIPTION
**Pull request by HussainTaj-arbisoft**
### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-hugo-themes/pull/1371 and https://github.com/mitodl/hq/issues/3858

### Description (What does it do?)

In https://github.com/mitodl/ocw-hugo-themes/pull/1371 we fixed a markdown rendering issue. The fix changes the HTML layout of the `collapsed-description` div.

We used to have this layout
```html
<div>
  text text text <button></button>
</div>
```

The fix changes it to 
```html
<div>
  <p>text text text</p>
  <button></button>
</div>
```

This introduces a line break that changes how the "See more" button is placed.

Screenshot 2024-03-28 at 12 00 22 PM

> What it should look like

Screenshot 2024-03-28 at 12 00 41 PM

> What it looks like on RC right now

### Screenshots (if appropriate):

Screenshot 2024-03-28 at 12 04 25 PM

### How can this be tested?

1. Grab contents of [this course](https://github.mit.edu/ocw-content-rc/sts.050-spring-2016).
2. Navigate to your local `ocw-hugo-themes` setup.
3. Run
    ```
    yarn start course sts.050-spring-2016
    ```
4. Open http://localhost:3000/
5. Observe the homepage.
6. Expect to see the description (collapses and expanded) rendered correctly. Please see the screenshot for reference.

### CODE REVIEW

**Comment by pdpinch** [comment]
Is there a way to add a test to this? Is a visual test necessary (like Percy) or can this be done with playwright?

**Comment by HussainTaj-arbisoft** [comment]
> Is there a way to add a test to this? Is a visual test necessary (like Percy) or can this be done with playwright?

Yes, Playwright has [visual comparison](https://playwright.dev/docs/test-snapshots) tests that we can use. I'll write a quick test.

I think Percy would be better but I don't have any experience using it. @pdpinch, do we have Percy set up for this project?

**Comment by HussainTaj-arbisoft** [comment]
@ibrahimjaved12, I'm going to try adding some visual tests. I'll let you know when it's ready for review again.

**Comment by HussainTaj-arbisoft** [comment]
@ibrahimjaved12, @pdpinch, I experimented with adding Playwright visual tests. We require a more thorough plan to use visual tests effectively.

To create reliable visual tests, we need consistent environments. Playwright tests are run on three environments local, GitHub Actions, and Concourse, and we always use the latest browsers for these tests. Under these conditions, visual tests are not robust and tend to fail in one environment or the other.

@pdpinch, should I write an issue to set up visual testing for this project?

I read the Percy starter docs and I think Percy would be easier to integrate and maintain than playwright visual tests. 

---

For now, I have added a test to validate CSS for this change (though this is not as reliable as a visual test would be).

**Review by gumaerc — APPROVED** [review]
👍 LGTM

@HussainTaj-arbisoft  FYI, I created an issue already to integrate Percy into our testing: https://github.com/mitodl/ocw-hugo-themes/issues/1340. Percy works in conjunction with an end to end testing framework like Playwright, so we can write Playwright tests and send snapshots to Percy in whichever tests we decide need visual testing.

> To create reliable visual tests, we need consistent environments. Playwright tests are run on three environments local, GitHub Actions, and Concourse, and we always use the latest browsers for these tests. Under these conditions, visual tests are not robust and tend to fail in one environment or the other.

Currently, the end to end tests run in Concourse are run against sites generated from different content then that of Github actions or local development. In the past we have discussed moving to a single source for end to end test content: https://github.com/mitodl/ocw-hugo-themes/issues/1271. Even so, differences in environments could possibly end up making the results of the build different, so I see what you're saying here. However, when you are creating a Percy snapshot you can pass it a string to identify that snapshot. If we passed some kind of environment string here, then the snapshots would be unique per environment. Likely we would want to have Percy snapshotting feature flagged though, as the free account only allows you 5000 snapshots per month. If we were performing this every time a Github actions run is done as well as running them in Concourse, we would probably run out of snapshots pretty quickly. If we limited visual testing to the Concourse pipeline, then the free amount of snapshots would probably be fine.

@pdpinch For what it's worth, when I have performed Percy snapshot comparisons in the past I set that up manually following the process in https://github.com/mitodl/ocw-hugo-themes/issues/1340. In order to add visual tests for new functionality as a part of our workflow, we would need to add Percy snapshotting to the applicable tests like I describe in that issue. We would likely want to feature flag it and only put snapshots on some of the tests, ideally things like the home page, etc. If we decide that visual testing is valuable and want to pay for more snapshotting, then we could consider expanding it to more tests at that point.

**Pull request merged**
