### PR TITLE
fix: duplicate IDs

### PR DESCRIPTION
**Pull request by MAbdurrehman12**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
- closes https://github.com/mitodl/ocw-hugo-themes/issues/1038
- Just realized, this PR also closes https://github.com/mitodl/ocw-hugo-themes/issues/1070 
    - FYI: @fakhar-ud-din Sorry about this, but if you want me to remove the changes fixing this issue, let me know

#### What's this PR do?
- Fixes all the duplicate IDs

#### How should this be manually tested?
- Checkout this branch
- Build any v2 course
- Verify that there are no duplicate IDs.
    - Duplicate IDs can be found using the JS snippet provided in this [comment](https://github.com/mitodl/ocw-hugo-themes/issues/1038#issuecomment-1420690916) 
- Verify that everything in the course (including CHP, interior pages, etc) works as expected and there are no side effects of these changes.
- Repeat this for course-v3 too

### CODE REVIEW

**Comment by gumaerc** [comment]
Looks like @ChristopherChudzicki is reviewing this but I checked it out as well and it looks good to me :+1:

**Comment by MAbdurrehman12** [comment]
> Don't worry about course-v3. As it stands, it's currently only an old duplicate of course-v2 and the changes I'm going to make to it are being held up by other work. Likely before I start making changes there, I'll just overwrite it again with the current state of course-v2.

Thanks for letting me know :)

**Review by ChristopherChudzicki — CHANGES_REQUESTED** [review]
We noticed two more duplicate IDs on course homepages, specifically `9.40-spring-2018`:

```
Duplicate id: #speciality-container_mobile_2_0
Duplicate id: #speciality-container__2_0
Total Duplicate IDs count: 2
```

**Comment by MAbdurrehman12** [comment]
@ChristopherChudzicki Please have another look

**Review by ChristopherChudzicki — APPROVED** [review]
👍

**Pull request merged**
