### PR TITLE
upgraded webpack

### LINKED ISSUE #778: Webpack Issue with Node v18.4.0
### Steps to Reproduce

Run `npm run start:course` with a valid `.env` file. Note that this error happens with Node v18.4.0 (the latest stable version), but not Node v16.5.1 LTS.

### Expected Behavior

The course website is generated and served locally.

### Actual Behavior

The command fails with the errors:

```
[start:webpack] Error: error:0308010C:digital envelope routines::unsupported
[start:webpack]   at new Hash (node:internal/crypto/hash:67:19)
[start:webpack]   at Object.createHash (node:crypto:133:10)
[start:webpack] opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[start:webpack]  library: 'digital envelope routines',
[start:webpack]  reason: 'unsupported',
[start:webpack]  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #778 

#### What's this PR do?
This PR updates webpack module

#### How should this be manually tested?
- Optional: Install `n` through npm (node version manager)
- Upgrade node to v18
- Verify npm run start:course works as expected
- Downgrade node to v16
- Verify npm run start:course works as expected

#### Any Background Context ? 
Upgraded webpack and peer dependencies to latest version. There are a few breaking changes in the following packages
- Expose Loader
- MiniCssExtractor
In the case of expose-loader the API Schema was changed and This PR webpack config to match the new config. For MiniCSSLoader the following options were removed from plugin and loader constructor.
 - MiniCssExtractor.loader
      - filename
      - chunkFileName
      - hmr
 - MiniCSSExtractor.Plugin
     - publicPath

### CODE REVIEW

**Review by pt2302 — CHANGES_REQUESTED** [review]
Getting issues with other dependencies on a clean `yarn install`.
```
warning " > babel-loader@8.2.2" has unmet peer dependency "@babel/core@^7.0.0".
warning " > dotenv-webpack@2.0.0" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning " > expose-loader@0.7.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > mini-css-extract-plugin@0.8.2" has incorrect peer dependency "webpack@^4.4.0".
warning " > optimize-css-assets-webpack-plugin@5.0.4" has incorrect peer dependency "webpack@^4.0.0".
warning " > react-dotdotdot@1.2.3" has unmet peer dependency "prop-types@*".
warning " > videojs-transcript-ac@0.8.8" has incorrect peer dependency "video.js@^5.6.0".
warning " > webpack-cli@3.3.12" has incorrect peer dependency "webpack@4.x.x".
```

**Comment by gumaerc** [comment]
@Wassaf-Shahzad Thanks for this, but I think we should make some additions here.  In addition to updating webpack, we should update all of the plugins we use as well because they are pinned to versions written to work with webpack 4.  When you run the webpack build a number of warnings show up:

```
warning " > babel-loader@8.2.2" has unmet peer dependency "@babel/core@^7.0.0".
warning " > dotenv-webpack@2.0.0" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning " > expose-loader@0.7.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > mini-css-extract-plugin@0.8.2" has incorrect peer dependency "webpack@^4.4.0".
warning " > optimize-css-assets-webpack-plugin@5.0.4" has incorrect peer dependency "webpack@^4.0.0".
warning " > react-dotdotdot@1.2.3" has unmet peer dependency "prop-types@*".
warning " > videojs-transcript-ac@0.8.8" has incorrect peer dependency "video.js@^5.6.0".
warning " > webpack-cli@3.3.12" has incorrect peer dependency "webpack@4.x.x".
```

These are all webpack plugins we use.  You should go through updating them one by one to the latest version, checking the webpack build after each upgrade.  There may be syntax changes needed to the webpack config as you update them.  Also, some other things should be tested:

 - make sure all independent bundles are generated and load the proper css / js in both course and www themes
 - make sure webpack built dependencies work properly i.e. mathjax, videojs, more basic stuff like jquery, etc.
 - make sure instructor insights specific css loads properly

**Comment by gumaerc** [comment]
@Wassaf-Shahzad I see you have started conditionally using `style-loader`:

```
          process.env.NODE_ENV === "production" ?
            "style-loader" :
            {
              loader:  MiniCssExtractPlugin.loader,
              options: {
                publicPath: "./"
              }
            },
```

I assume that you did this because of how they say "Do not use style-loader and mini-css-extract-plugin together" [here](https://webpack.js.org/loaders/style-loader/).  I think we should remove `style-loader` altogether, as I don't believe it's even being used.  The whole point of `style-loader` is that it's supposed to inject `style` tags directly into the DOM.  It's typically used in development for faster loading of pages in conjunction with Hot Module Reload.  Since our HTML is all being generated by Hugo and not processed by Webpack (aside from the search app) we don't get much / any benefit from it.  Furthermore, the exclusion of `MiniCssExtractPlugin.loader` in production means that the CSS filenames are not making it into the `webpack.json` file that tells Hugo where those files are.  You can see this if you run `npm run build:webpack` and inspect the `webpack.json` file.  Therefore, I think we should change the CSS loader block to just look like this:

```
      {
        test: /\.(sa|sc|c)ss$/,
        use:  [
          {
            loader:  MiniCssExtractPlugin.loader,
            options: {
              publicPath: "./"
            }
          },
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
      },
```

**Comment by gumaerc** [comment]
I tried the updated code and the CSS file names are showing up now:

```
  "main": {
    "css": "/static/css/main.1d29b.css",
    "js": "/static/js/main.1d29b.js"
  },
```

I think there are maybe a few more deprecations we should look into before we merge this:

```
(node:187109) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:187109) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(node:187109) [DEP_WEBPACK_COMPILATION_CACHE] DeprecationWarning: Compilation.cache was removed in favor of Compilation.getCache()
(node:187109) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
```

**Comment by pt2302** [comment]
Warnings on a clean `yarn install`:
```
warning " > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
warning " > optimize-css-assets-webpack-plugin@6.0.1" has incorrect peer dependency "webpack@^4.0.0".
warning " > react-dotdotdot@1.3.1" has unmet peer dependency "prop-types@*".
warning " > videojs-transcript-ac@0.8.8" has incorrect peer dependency "video.js@^5.6.0".
```

**Comment by Wassaf-Shahzad** [comment]
> Warnings on a clean `yarn install`:
> 
> ```
> warning " > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > optimize-css-assets-webpack-plugin@6.0.1" has incorrect peer dependency "webpack@^4.0.0".
> warning " > react-dotdotdot@1.3.1" has unmet peer dependency "prop-types@*".
> warning " > videojs-transcript-ac@0.8.8" has incorrect peer dependency "video.js@^5.6.0".
> ```

@pt2302, I looked into this and discovered the following
- For some reason yarn install does not install babel/core@7.0.0, I even tried cleaning my yarn cache.
- optimize-css-assets-webpack-plugin is already the latest version.
- For react-dotdotdot@1.3.1, we already have prop-types installed as dependency
-  videojs-transcript-ac@0.8.8 is the latest version and the solution for this is to downgrade videoJS itself which can cause problems

**Comment by pt2302** [comment]
At the latest commit (https://github.com/mitodl/ocw-hugo-themes/pull/787/commits/68e10c7b0c3007c8908f05d78dc2144b94e4a8b5), warnings on a clean `yarn install`:
```
warning " > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
warning " > react-dotdotdot@1.3.1" has unmet peer dependency "prop-types@*".
warning " > videojs-transcript-ac@0.8.8" has incorrect peer dependency "video.js@^5.6.0".
```

**Comment by pt2302** [comment]
Per discussion with @gumaerc, the above warnings do not appear to be related to the webpack upgrade, so can be part of a separate issue.

**Review by pt2302 — APPROVED** [review]
Tested locally, and this looks good to me!

**Pull request merged**
