### PR TITLE
Update give button and adjust link size in promo carousel

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes https://github.com/mitodl/ocw-www/issues/105

#### What's this PR do?
Update give button and increase link size a bit for carousel link

#### How should this be manually tested?
Look at home page

#### Screenshots
Screenshot from 2021-05-24 11-54-49

Screenshot from 2021-05-24 11-54-36

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
The Give Now button LGTM.  Issue #105 also mentions tweaking the style of the "Give Now" link in the top menu (Orange background, black text - I assume this is when hovering over it) - is that going to be in a separate PR?

**Comment by noisecapella** [comment]
@mbertrand Thanks, that was an oversight. I'll include it in this PR

**Comment by noisecapella** [comment]
@mbertrand 
Screenshot from 2021-05-25 18-45-53

**Comment by noisecapella** [comment]
From the issue I think it is meant to be there all the time, not just on hover. It is changed for better contrast

**Review by mbertrand — APPROVED** [review]
Looks great! 👍

**Pull request merged**
