### PR TITLE
Fixed newsletter and contact

### LINKED ISSUE #620: Contact us page has left spacing issues
### Steps to Reproduce
On my mobile device, the "contact us" page renders such that the form fields begin off screen and text in general has no spacing on the left.

Device: iPhone 12 Pro, v15.3.1

### Expected Behavior

The alignment of the text and input fields should render with proper spacing on the left. 
 
### Actual Behavior
In the screenshot, we see that the input fields start off screen and the text has zero space on the left.

### Screenshot or Screencast
File

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
closes #620 

#### What's this PR do?
fixed spacing issue in contact and newsletter page

#### How should this be manually tested?
Verify there is appropriate margin in mobile screen for the following pages
- Contact
- Newsletter

#### Screenshots (if appropriate)
Screenshot 2022-04-11 at 10 19 35 AM
Screenshot 2022-04-11 at 10 19 28 AM
Screenshot 2022-04-11 at 10 19 10 AM

### CODE REVIEW

**Review by MAbdurrehman12 — CHANGES_REQUESTED** [review]
Looks good!

Just a nitpick: I think, for mobile and tab screens, we can keep the padding: `px-3` and for rest of the bigger screens `px-5` so it becomes consistent with the other pages.
Currently, these 2 pages have more left/right spacing than the other pages (about, educator etc):
e.g: 
Contact: 
image

Educator:
image

About:
image

(Ideally, we should apply a same class of paddings/margins on all pages (maybe add padding in `page-single` class) for better consistency and maintainability but I'm not sure it will be easy enough at this stage so I think we can stick to the current solution)

**Review by MAbdurrehman12 — APPROVED** [review]
Looks good!

**Comment by dseaton** [comment]
From a user perspective - looks great! Thank you!

**Comment by pdpinch** [comment]
Consistency is valuable, even if it means a larger diff at this time. 

I need to open an issue about the about page not having enough left margin as well...

**Comment by Wassaf-Shahzad** [comment]
> Consistency is valuable, even if it means a larger diff at this time.
> 
> I need to open an issue about the about page not having enough left margin as well...

@pdpinch 
I can fix the with this PR as well

**Pull request merged**
