### PR TITLE
fixed nav items

### LINKED ISSUE #825: course-v2: left nav
#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/468374061/preview?scrollOffset=299

#### Acceptance Criteria:

- [ ] the font size should be consistent. Currently the sub-menu font is smaller than the menu font
- [ ] the clickable area should include the white space between the text and the downward arrow.

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #825 

#### What's this PR do?
Fixes the following
- Makes sub-menues the same font size as parents
- Makes space between title and arrow clickable

#### How should this be manually tested?
- Start ocw-course
- On the left nav verify clicking empty space between nav item and arrow behaves similar to either the nav-item or arrow depending on distance.
- Verify sub-menu font size is similar to parent

#### Screenshots (if appropriate)

Screenshot 2022-08-16 at 4 27 15 PM

### CODE REVIEW

**Comment by MAbdurrehman12** [comment]
> the clickable area should include the white space between the text and the downward arrow.

@pdpinch The white space area that has been made clickable now: is this click intended for toggling the arrow or opening the link?

**Review by MAbdurrehman12 — CHANGES_REQUESTED** [review]
Apart from this [question](https://github.com/mitodl/ocw-hugo-themes/pull/826#issuecomment-1219493175), it looks like all the white space area between the text and down arrow is not clickable. 
The area next to the text is clickable but as we move forward to the down arrow button, the margined area next to it becomes un-clickable. 
For reference, please see this video: 

https://user-images.githubusercontent.com/93309234/185620567-44be6a98-f432-41f6-946f-cefcdf2fde3d.mov

This is due to this [left margin](https://github.com/mitodl/ocw-hugo-themes/blob/c2dbea19627e14a203ce8cddb90af6f1523ba92a/course-v2/assets/css/course-nav.scss#L49).

Maybe we can make this margined area clickable and upon clicking, it toggles the arrow button?
and area next to the text, upon clicking, opens/redirects us to the link?

**Comment by Wassaf-Shahzad** [comment]
> Apart from this [question](https://github.com/mitodl/ocw-hugo-themes/pull/826#issuecomment-1219493175), it looks like all the white space area between the text and down arrow is not clickable. The area next to the text is clickable but as we move forward to the down arrow button, the margined area next to it becomes un-clickable. For reference, please see this video:
> 
>  nav.list.items.mov 
> This is due to this [left margin](https://github.com/mitodl/ocw-hugo-themes/blob/c2dbea19627e14a203ce8cddb90af6f1523ba92a/course-v2/assets/css/course-nav.scss#L49).
> 
> Maybe we can make this margined area clickable and upon clicking, it toggles the arrow button? and area next to the text, upon clicking, opens/redirects us to the link?

@pdpinch, Need your  input on this

**Comment by dseaton** [comment]
> > the clickable area should include the white space between the text and the downward arrow.
> 
> @pdpinch The white space area that has been made clickable now: is this click intended for toggling the arrow or opening the link?

I think there is some ambiguity about what the clickable whitespace should do; I can't find specifics in the issue history or wireframes.  To unblock you, follow @MAbdurrehman12 's advice and make the left-margin by the arrow clickable, so that it toggles the submenu. @pdpinch might clarify this next week, but I think this will let you merge and keep moving.

**Comment by Wassaf-Shahzad** [comment]
> Apart from this [question](https://github.com/mitodl/ocw-hugo-themes/pull/826#issuecomment-1219493175), it looks like all the white space area between the text and down arrow is not clickable. The area next to the text is clickable but as we move forward to the down arrow button, the margined area next to it becomes un-clickable. For reference, please see this video:
> 
>  nav.list.items.mov 
> This is due to this [left margin](https://github.com/mitodl/ocw-hugo-themes/blob/c2dbea19627e14a203ce8cddb90af6f1523ba92a/course-v2/assets/css/course-nav.scss#L49).
> 
> Maybe we can make this margined area clickable and upon clicking, it toggles the arrow button? and area next to the text, upon clicking, opens/redirects us to the link?

Removed margin since they are not part to the html box model and can not be made clickable.
Screenshot 2022-08-23 at 2 57 29 PM

**Comment by dseaton** [comment]
Rebase aside, I think this satisfies what Peter had in #825.

**Review by MAbdurrehman12 — APPROVED** [review]
Looks good 👍

**Pull request merged**
