### PR TITLE
Video pages layout width-fix

### PR DESCRIPTION
**Pull request by ibrahimjaved12**
### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/2921

### Description (What does it do?)
Removes `max-width: 100vh` from video pages styling to allow the content to spread over all of the `div` body.
This means, not only the text, but videos will now take up entire `div` width too.

### Screenshots
Refer to https://github.com/mitodl/ocw-hugo-themes/pull/1369#issuecomment-1993747002

### How can this be tested?
Checkout to this branch, check any course that has video lectures (the default course also does -- `yarn start course`). Check embed video pages as well. An example of embed video is in course `18.06sc-fall-2011` in the Instructor Insights page.

For offline course theme, run:
`yarn build ~/path/ocw-content-rc/18.06sc-fall-2011/ ~/path/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`
And then open `index.html` from `dist` directory of the course, and navigate to videos. Replace course-id with course of your choice.

### CODE REVIEW

**Comment by pdpinch** [comment]
Does the div have a maximum width? 

I know that on desktop views, we don't like to extend the text (and the video) too much. At really wide widths, it becomes hard to read (See, for example, the layouts of medium.com or nytimes.com)

**Comment by ibrahimjaved12** [comment]
> Does the div have a maximum width?
> 
> I know that on desktop views, we don't like to extend the text (and the video) too much. At really wide widths, it becomes hard to read (See, for example, the layouts of medium.com or nytimes.com)

@pdpinch The webpage has dynamic max-width (fixed max widths, but different for different screens)
For desktop view, we have a `max-width` of 1447px for the entire webpage (which is centered)

From this, the video area `div` has `max-width` of 75% of the total width
image
Even if we close the right course info bar, then the video area takes its space, but only its space, not more than that

So our design is very similar to those websites
image
image


Previously we had this exact problem with the header and footers - that they would just spread around on left/right corners, for larger screens. But we fixed that recently.

**Comment by ChristopherChudzicki** [comment]
@ibrahimjaved12: The `max-width: 100vh` was set in #898 to fix #865 ... Basically, the video playwer was getting too large and people couldn't see the controls.

From your screenshots, it looks like this change does NOT re-introduce #865 (good). But IMO worth double checking the reproduction steps in #865. **Note:** When #865 was reported, we were using a different video player, and subsequently switched to the YouTube player. So, assuming #865 has no resurfaced, that's one possible explanation for why.

**Comment by ibrahimjaved12** [comment]
Kind of restrained by video player's entire transcript to be seen requirement, this is what I thought of.
Video player stays same as before, but we allow the textual content to take screen's allocated `max-width` (max-width of `xs`, `s`, `md`, `lg`, etc)

image

Basically you will see in the first pic in this screenshot, previously the text was same width as video player, but now its taking all the space it needs.

**Comment by ibrahimjaved12** [comment]
This PR is again ready for review

**Comment by pdpinch** [comment]
Ok, I think this is the best compromise we can get. It allows for the video and the transcript to both be in view. 

If the user really wants a full-wdith video, they can tap the full screen button.

**Review by gumaerc — APPROVED** [review]
👍 This looks fine to me. I find myself wondering if we could take a different approach to fullscreening the video though. According to https://developers.google.com/youtube/player_parameters, we can pass `fs=0` to disable the fullscreen button within the YouTube player. Then, in theory, we could provide our own fullscreen button. We could then use the `:fullscreen` pseudo class to define our own fullscreen layout. This layout could place the transcript on the right side of the video in landscape, and at the bottom of the video in portrait. In theory, anyway. I think that this could maybe be worth it, but it depends on how many people watch OCW videos in this manner. As @pdpinch mentioned, they can fullscreen the video and turn on closed captioning in YouTube which will provide the transcript. The only functionality this doesn't offer is scrolling through the transcript and clicking a line to seek there in the video. If we provided a custom fullscreen layout, then this would be possible.

**Comment by ibrahimjaved12** [comment]
> 👍 This looks fine to me. I find myself wondering if we could take a different approach to fullscreening the video though. According to https://developers.google.com/youtube/player_parameters, we can pass `fs=0` to disable the fullscreen button within the YouTube player. Then, in theory, we could provide our own fullscreen button. We could then use the `:fullscreen` pseudo class to define our own fullscreen layout. This layout could place the transcript on the right side of the video in landscape, and at the bottom of the video in portrait. In theory, anyway. I think that this could maybe be worth it, but it depends on how many people watch OCW videos in this manner. As @pdpinch mentioned, they can fullscreen the video and turn on closed captioning in YouTube which will provide the transcript. The only functionality this doesn't offer is scrolling through the transcript and clicking a line to seek there in the video. If we provided a custom fullscreen layout, then this would be possible. For example, the Twitch video player provides similar functionality with their "theater mode" button which makes the video take up all available space in the browser window aside from a column on the right hand side for the chat. We could create a similar layout, but with a transcript instead of live stream chat.

Thanks @gumaerc. I like the idea. For now, I'm going to merge this PR. But I'll R&D / experiment on this and see how we could go with this.

**Pull request merged**
